include ../../dep.def
SUBPACKAGE=mmscore
TARGET=libmmscore.so
LOCAL_INC=$(DIRECTFB_INC) $(SIGC_INC) $(LIBXML_INC) $(CURL_INC) $(XINE_INC) $(GSTREAMER_INC) $(PJ_INC)
LOCAL_LIBS=
include ../../shlib.def
