include ../../dep.def
SUBPACKAGE=mmstools
TARGET=libmmstools.so
STATIC_TARGET=libmmstools.a
LOCAL_INC=$(LIBXML_INC) $(DIRECTFB_INC) $(CURL_INC) $(SQLITE3_INC) $(MYSQL_INC) $(FREETDS_INC) $(OPENSSL_INC) $(SIGC_INC) $(VMIME_INC)
LOCAL_LIBS=
include ../../shlib.def
