include ../../dep.def

#check private dependencies
TARGET=taff
LOCAL_INC=$(SIGC_INC) $(DIRECTFB_INC) $(LIBXML_INC) $(XINE_INC) $(GSTREAMER_INC) $(PJ_INC)
LOCAL_LIBS=-lmmsinfo -lmmsconfig -lmmscore -lmmsmedia -lmmsinput -lmmsgui -lmmsbase -lmmstools $(CURL_LIBS) $(SIGC_LIBS) $(LIBPNG_LIBS) $(LIBXML_LIBS) $(SQLITE3_LIBS) $(MYSQL_LIBS) $(FREETDS_LIBS) $(DIRECTFB_LIBS) $(OPENSSL_LIBS) $(XINE_LIBS) $(GSTREAMER_LIBS) $(ALSA_LIBS) $(X11_LIBS) $(VMIME_LIBS) -lrt $(PJ_LIB)
include ../../bin.def
