include ../../dep.def
SUBPACKAGE=mmsconfig
TARGET=libmmsconfig.so
STATIC_TARGET=libmmsconfig.a
LOCAL_INC=$(LIBXML_INC) $(SQLITE3_INC) $(MYSQL_INC) $(FREETDS_INC) $(SIGC_INC)
LOCAL_LIBS=
include ../../shlib.def
